version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: employee-postgres
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - employee-network

volumes:
  postgres_data:

networks:
  employee-network:
    driver: bridge